FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app_be
# app_be: apliacacion backend
COPY ./back_end /app_be/

RUN pip install -r requirements.txt

EXPOSE 9000

CMD sh -c "python3 manage.py makemigrations --noinput && python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:9000"





