# Generated by Django 3.0.8 on 2024-03-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240303_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='coin',
            field=models.CharField(choices=[('$USD', '$USD'), ('$ARS', '$ARS'), ('€EUR', '€EUR')], default='$ARS', max_length=6),
        ),
    ]
