name: Run Tests

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest  # Or a preferred runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose@v2  # Use the recommended v2 action
        with:
          up-args: -d  # Run services in detached mode

      - name: Build and start services (if not already running)
        run: docker-compose up -d --build  # Only build if necessary

      - name: Install test dependencies (if needed)
        run: docker-compose run backend pip install -r requirements.txt  # Adjust path as needed

      - name: Run tests
        run: docker-compose run --rm backend python3 manage.py test api.tests

      - name: Upload test reports (optional)
        uses: actions/upload-artifact@v3  # Store test results for analysis
        if: always  # Always upload results, even for failures
        with:
          name: test-reports
          path: backend/test_results  # Or a custom directory

      - name: Stop services (optional)
        run: docker-compose down  # Stop containers for cleanup
