name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: ait_prueba_tecnica
          MYSQL_USER: facu
          MYSQL_PASSWORD: Facu1234@
          MYSQL_ROOT_PASSWORD: Facu1234@
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" 
          --health-interval=30s 
          --health-timeout=10s 
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run containers
        run: |
          docker-compose up --build -d
          sleep 30  # Espera a que MySQL esté listo

      - name: Run migrations and tests
        run: |
          docker-compose exec backend python3 manage.py makemigrations --noinput
          docker-compose exec backend python3 manage.py migrate --noinput
          docker-compose exec backend python3 manage.py test
          
      - name: Stop and remove containers
        run: docker-compose down
