name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    - name: Build and run backend container
      run: |
        docker compose -f docker-compose.yml up -d
        sleep 10  

    - name: Grant privileges to user
      run: |
        docker exec -i db_mysql_dk mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON *.* TO 'facu'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"

    - name: Run tests
      run: |
        docker compose -f docker-compose.yml run backend sh -c "python3 manage.py test api.tests"

    - name: Stop services
      run: docker compose -f docker-compose.yml down

